services:
  mlflow:
    container_name: mlflow_server
    build: 
      network: host
      context: .
      dockerfile: Dockerfile
    command:
      - bash
      - -c
      - "mlflow server --backend-store-uri sqlite:////mlflow/mlflow.db --serve-artifacts --host 0.0.0.0 --port 5000"
    ports:
      - "5000:5000"
    volumes:
      - ./run_env/data:/mlflow
    extra_hosts:
      - "localhost:0.0.0.0"